# Mapeo de municipios a comarcas de Cantabria
MUNICIPIOS_COMARCAS = {
    # Comarca Santander
    'Santander': 'Santander',

    # Comarca Trasmiera
    'Arnuero': 'Trasmiera',
    'Bareyo': 'Trasmiera',
    'Escalante': 'Trasmiera',
    'Meruelo': 'Trasmiera',
    'Noja': 'Trasmiera',
    'Ribamontan al Mar': 'Trasmiera',
    'Ribamontan al Monte': 'Trasmiera',
    'Solares': 'Trasmiera',
    'Marina de Cudeyo': 'Trasmiera',
    'Medio Cudeyo': 'Trasmiera',
    'Entrambasaguas': 'Trasmiera',
    'Hoznayo': 'Trasmiera',
    'Liérganes': 'Trasmiera',
    'Penagos': 'Trasmiera',
    'Riotuerto': 'Trasmiera',
    'Soto de la Marina': 'Trasmiera',
    'Miera': 'Trasmiera',

    # Comarca Ason-Aguera
    'Ampuero': 'Ason-Aguera',
    'Arredondo': 'Ason-Aguera',
    'Guriezo': 'Ason-Aguera',
    'Liendo': 'Ason-Aguera',
    'Rasines': 'Ason-Aguera',
    'Ramales de la Victoria': 'Ason-Aguera',
    'Ruesga': 'Ason-Aguera',
    'Soba': 'Ason-Aguera',
    'Solorzano': 'Ason-Aguera',
    'Voto': 'Ason-Aguera',

    # Comarca Costa Oriental
    'Castro-Urdiales': 'Costa Oriental',
    'Laredo': 'Costa Oriental',
    'Colindres': 'Costa Oriental',
    'Limpias': 'Costa Oriental',
    'Santoña': 'Costa Oriental',
    'Barcena de Cicero': 'Costa Oriental',
    'Argoños': 'Costa Oriental',
    'Hazas de Cesto': 'Costa Oriental',
    'Cicero': 'Costa Oriental',

    # Comarca Valles Pasiegos
    'San Roque de Riomiera': 'Valles Pasiegos',
    'San Pedro del Romeral': 'Valles Pasiegos',
    'Vega de Pas': 'Valles Pasiegos',
    'Selaya': 'Valles Pasiegos',
    'Villacarriedo': 'Valles Pasiegos',
    'Corvera de Toranzo': 'Valles Pasiegos',
    'Santiurde de Toranzo': 'Valles Pasiegos',

    # Comarca Costa Occidental
    'Alfoz de Lloredo': 'Costa Occidental',
    'Comillas': 'Costa Occidental',
    'Ruiloba': 'Costa Occidental',
    'San Vicente de la Barquera': 'Costa Occidental',
    'Santillana del Mar': 'Costa Occidental',
    'Suances': 'Costa Occidental',
    'Udias': 'Costa Occidental',
    'Val de San Vicente': 'Costa Occidental',
    'Valdaliga': 'Costa Occidental',
    'Reocin': 'Costa Occidental',
    'Cóbreces': 'Costa Occidental',
    'Viveda': 'Costa Occidental',

    # Comarca Saja-Nansa
    'Cabuérniga (Valle de)': 'Saja-Nansa',
    'Herrerias': 'Saja-Nansa',
    'Lamason': 'Saja-Nansa',
    'Mazcuerras': 'Saja-Nansa',
    'Polaciones': 'Saja-Nansa',
    'Rionansa': 'Saja-Nansa',
    'Ruente': 'Saja-Nansa',
    'Los Tojos': 'Saja-Nansa',
    'Tudanca': 'Saja-Nansa',

    # Comarca Besaya
    'Torrelavega': 'Besaya',
    'Cartes': 'Besaya',
    'Los Corrales de Buelna': 'Besaya',
    'Cieza': 'Besaya',
    'San Felices de Buelna': 'Besaya',
    'Suances': 'Besaya',
    'Polanco': 'Besaya',
    'Barcena de Pie de Concha': 'Besaya',
    'Molledo': 'Besaya',
    'Arenas de Iguña': 'Besaya',
    'Anievas': 'Besaya',
    'Cieza': 'Besaya',
    'Penagos': 'Besaya',
    'Puente Viesgo': 'Besaya',
    'Villasuso (Anievas)': 'Besaya',
    'Herrera de Ibio': 'Besaya',

    # Comarca Campoo-Los Valles
    'Reinosa': 'Campoo-Los Valles',
    'Campoo de Enmedio': 'Campoo-Los Valles',
    'Campoo de Yuso': 'Campoo-Los Valles',
    'Hermandad de Campoo de Suso': 'Campoo-Los Valles',
    'Las Rozas': 'Campoo-Los Valles',
    'Luena': 'Campoo-Los Valles',
    'Mancomunidad Campoo-Cabuérniga': 'Campoo-Los Valles',
    'Pesaguero': 'Campoo-Los Valles',
    'Pesquera': 'Campoo-Los Valles',
    'San Miguel de Aguayo': 'Campoo-Los Valles',
    'Santiurde de Reinosa': 'Campoo-Los Valles',
    'Valdeolea': 'Campoo-Los Valles',
    'Valdeprado del Río': 'Campoo-Los Valles',
    'Valderredible': 'Campoo-Los Valles',
    'Valle de Villaverde': 'Campoo-Los Valles',

    # Comarca Liebana
    'Potes': 'Liebana',
    'Cabezon de Liébana': 'Liebana',
    'Camaleño': 'Liebana',
    'Cillorigo': 'Liebana',
    'Peñarrubia': 'Liebana',
    'Tresviso': 'Liebana',
    'Vega de Liébana': 'Liebana',

    # Otros municipios de la Bahia de Santander
    'Camargo': 'Santander',
    'El Astillero': 'Santander',
    'Santa Cruz de Bezana': 'Santander',
    'Piélagos': 'Santander',
    'Villaescusa': 'Santander',
    'Santa Maria de Cayon': 'Santander',
    'Miengo': 'Santander',
    'Castañeda': 'Santander',

    # Municipios adicionales
    'Ajo': 'Costa Oriental',
    'Beranga': 'Ason-Aguera',
    'Boo': 'Trasmiera',
    'Cabezon de la Sal': 'Saja-Nansa',
    'Carrejo': 'Besaya',
    'Casar de Periedo': 'Besaya',
    'Cuchia': 'Trasmiera',
    'Cudon': 'Trasmiera',
    'Guarnizo': 'Santander',
    'Heras': 'Trasmiera',
    'Isla': 'Santander',
    'Maoño': 'Costa Oriental',
    'Mogro': 'Costa Occidental',
    'Mompia': 'Trasmiera',
    'Pontejos': 'Santander',
    'Puente San Miguel': 'Besaya',
    'Saro': 'Besaya',
    'Sobremazas': 'Valles Pasiegos',
    'Villafufre': 'Valles Pasiegos',
    'Villanueva': 'Valles Pasiegos',
    'Villapresente': 'Valles Pasiegos',
}

def obtener_comarca(municipio):
    """Obtiene la comarca de un municipio"""
    return MUNICIPIOS_COMARCAS.get(municipio, 'Desconocida')
